// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLdami3OZIfDMcNdn6SIWsD7-0z8bJ1Mw',
    appId: '1:13241645392:web:c9a32b9b56be4323a45455',
    messagingSenderId: '13241645392',
    projectId: 'capp-a331b',
    authDomain: 'capp-a331b.firebaseapp.com',
    storageBucket: 'capp-a331b.firebasestorage.app',
    measurementId: 'G-3S24RWVN9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFO89LW9QAWY4Z-OZnZJJ9ILnjbMnKn6A',
    appId: '1:13241645392:android:f9927433685734e2a45455',
    messagingSenderId: '13241645392',
    projectId: 'capp-a331b',
    storageBucket: 'capp-a331b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU3OSWfraWw3OUjrIL8OD1h85HGoQNcM0',
    appId: '1:13241645392:ios:6dd198581fd5b2bda45455',
    messagingSenderId: '13241645392',
    projectId: 'capp-a331b',
    storageBucket: 'capp-a331b.firebasestorage.app',
    iosBundleId: 'br.com.capp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU3OSWfraWw3OUjrIL8OD1h85HGoQNcM0',
    appId: '1:13241645392:ios:6dd198581fd5b2bda45455',
    messagingSenderId: '13241645392',
    projectId: 'capp-a331b',
    storageBucket: 'capp-a331b.firebasestorage.app',
    iosBundleId: 'br.com.capp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLdami3OZIfDMcNdn6SIWsD7-0z8bJ1Mw',
    appId: '1:13241645392:web:36a7769aa3fd0e4da45455',
    messagingSenderId: '13241645392',
    projectId: 'capp-a331b',
    authDomain: 'capp-a331b.firebaseapp.com',
    storageBucket: 'capp-a331b.firebasestorage.app',
    measurementId: 'G-GFX7Y4WXYP',
  );
}
